# Pre-build script: embed embed/pages/*.jsonl into the firmware partition and
# generate a name -> blob registry in src/hasp_embed_pages.cpp.
#
# Enable per env in platformio_override.ini:
#   extra_scripts =
#       ${esp32.extra_scripts}
#       pre:tools/embed_pages_register.py
#
# Files placed in embed/pages/ are linked into the app binary (not LittleFS),
# so they are not visible from the web UI / FTP / file listing.

Import("env")

import glob
import os
import re

EMBED_DIR = "embed/pages"
OUT_FILE = os.path.join("src", "hasp_embed_pages.cpp")


def to_sym(rel_path):
    rel_path = rel_path.replace("\\", "/")
    return "_binary_" + re.sub(r"[^A-Za-z0-9]", "_", rel_path)


files = sorted(glob.glob(os.path.join(EMBED_DIR, "*.jsonl")))

if files:
    rel_files = [f.replace("\\", "/") for f in files]
    env.Append(CPPDEFINES=["HASP_USE_EMBED_PAGES"])

    # Append our files to board_build.embed_files for the current env so the
    # platform's _embed_files.py picks them up (it reads via GetProjectOption).
    config = env.GetProjectConfig()
    section = "env:" + env["PIOENV"]
    existing = env.GetProjectOption("board_build.embed_files", "") or ""
    parts = [p for p in (existing.splitlines() if isinstance(existing, str) else list(existing)) if p.strip()]
    parts.extend(rel_files)
    config.set(section, "board_build.embed_files", "\n".join(parts))

lines = []
lines.append("// AUTO-GENERATED by tools/embed_pages_register.py - do not edit")
lines.append('#include "hasp_embed_pages.h"')
lines.append("")
lines.append("#ifdef HASP_USE_EMBED_PAGES")
lines.append("#include <string.h>")
lines.append("#include <stdint.h>")
lines.append("")
for f in files:
    sym = to_sym(f)
    lines.append('extern const uint8_t {0}_start[] asm("{0}_start");'.format(sym))
    lines.append('extern const uint8_t {0}_end[]   asm("{0}_end");'.format(sym))
lines.append("")
lines.append("namespace {")
lines.append("struct EmbedPage { const char* name; const uint8_t* start; const uint8_t* end; };")
lines.append("const EmbedPage kEmbedPages[] = {")
for f in files:
    base = os.path.basename(f)
    sym = to_sym(f)
    lines.append('    {{ "{0}", {1}_start, {1}_end }},'.format(base, sym))
lines.append("};")
lines.append("const size_t kEmbedPagesCount = sizeof(kEmbedPages) / sizeof(kEmbedPages[0]);")
lines.append("} // namespace")
lines.append("")
lines.append('extern "C" const uint8_t* hasp_embed_find(const char* name, size_t* len) {')
lines.append("    if (!name) return nullptr;")
lines.append("    while (*name == '/') name++;")
lines.append("    for (size_t i = 0; i < kEmbedPagesCount; ++i) {")
lines.append("        if (strcmp(name, kEmbedPages[i].name) == 0) {")
lines.append("            if (len) *len = (size_t)(kEmbedPages[i].end - kEmbedPages[i].start);")
lines.append("            return kEmbedPages[i].start;")
lines.append("        }")
lines.append("    }")
lines.append("    return nullptr;")
lines.append("}")
lines.append("#else")
lines.append('extern "C" const uint8_t* hasp_embed_find(const char*, size_t*) { return nullptr; }')
lines.append("#endif")
lines.append("")

new_content = "\n".join(lines)

existing = ""
if os.path.exists(OUT_FILE):
    with open(OUT_FILE, "r") as fh:
        existing = fh.read()

if existing != new_content:
    with open(OUT_FILE, "w") as fh:
        fh.write(new_content)
    print("[embed_pages] wrote {0} ({1} entries)".format(OUT_FILE, len(files)))
else:
    print("[embed_pages] {0} up to date ({1} entries)".format(OUT_FILE, len(files)))
